blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/syn54x/mkdocs-typer2/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Q&A
    url: https://github.com/syn54x/mkdocs-typer2/discussions/new?category=q-a
    about: Ask and answer questions about the project
  - name: Documentation
    url: https://github.com/syn54x/mkdocs-typer2/discussions/new?category=documentation
    about: Suggest improvements or report issues with documentation
